### ISSUE TITLE
ECB Rate Provider not working in JavaMoney Demo Application

### ISSUE THREAD

**Issue by ghost** [JavaMoney/javamoney-examples#18]
The ECB Rate Provider isn't working for me in the JavaMoney Demo Application.  I am using NetBeans 8.0.2 and Default JDK 1.8.

Note that when I run my own sample application, ECB is cool with the 0.9 dependency and not for anything sooner...

 <dependency>
        <groupId>org.javamoney</groupId>
        <artifactId>moneta</artifactId>
        <version>0.9</version>
  </dependency>

Thanks,
Robert

**Comment by gliesian66** [comment]
My bad... looks like it works for supported conversions, e.g., USD -> EUR and throws exceptions when not supported.

**Comment by keilw** [comment]
Is this resolved?
Note, there is a moneta 1.0 now, too ;-)
