### ISSUE TITLE
Double e's in Access Exchange Rates JavaMoney Demo Application source

### ISSUE THREAD

**Issue by ghost** [JavaMoney/javamoney-examples#19]
CurrencyUnit base = MoneetaryCurrencies.getCurrency("EUR");
CurrencyUnit term = MoneetaryCurrencies.getCurrency("USD");

should read

CurrencyUnit base = MonetaryCurrencies.getCurrency("EUR");
CurrencyUnit term = MonetaryCurrencies.getCurrency("USD");

**Comment by stokito** [comment]
Could you say where you find it?

**Comment by keilw** [comment]
Sorry, this seems outdated, as of 1.0 Final the static accessor is just called **Monetary**.
If the example still refers to MonetaryCurrencies, we'll have to address that.
