### ISSUE TITLE
Custom Rate Provider

### ISSUE THREAD

**Issue by rosin1408** [JavaMoney/javamoney-examples#20]
HI, I'm trying to create a rate provider to get exchange rates from my database, but I can't found documentation about it. It's possible to do? How can I register this?

**Comment by keilw** [comment]
Please have a look at https://github.com/JavaMoney/javamoney-lib/tree/master/exchange/exchange-rate-yahoo. @otaviojava can probably help you as he was involved in adding Yahoo to javamoney-lib, too.

**Comment by rosin1408** [comment]
Thanks @keilw I will look this

**Comment by otaviojava** [comment]
Hi @rosin1408  if you have any question, please, let me know. 
Or sent an email to me: otaviojava@java.net

**Comment by rosin1408** [comment]
Hi @otaviojava 
I'll sent mail for you, thanks

**Comment by keilw** [comment]
@otaviojava Feel free to handle this ticket. If you want to keep it open till you help find a solution, no problem otherwise close it whenever you think the question is answered.

**Comment by otaviojava** [comment]
Thanks @keilw  and @rosin1408 
I am closing this issue
