### ISSUE TITLE
How to write custom ExchangeRateProvider 

### ISSUE THREAD

**Issue by kharemohit786** [JavaMoney/javamoney-examples#27]
I want to write custom exchange provider to provide the exchange rate manually with a csv file.

**Comment by keilw** [comment]
This example may not run right now, but it worked based on CSV files already: https://github.com/JavaMoney/javamoney-examples/tree/master/web/javamoney-tradingapp. Furthermore, javamoney-lib contains _ExchangeRateProvider _implementations for Yahoo, which is also CSV based.

**Comment by stokito** [comment]
You can take a look on [IdentityRateProvider.java](https://github.com/JavaMoney/jsr354-ri/blob/4cab8838260af222fa2d2b1cd2512bc1ae7ee1a9/moneta-convert/moneta-convert-base/src/main/java/org/javamoney/moneta/convert/internal/IdentityRateProvider.java) which is simplest provider which can be. In the same package you can find other rates providers.

Also here is more sophisticated rate provider fro cryptocurrencies
https://github.com/ConsensusJ/consensusj/blob/7b7ecc33038795e4e539cf9e991b3da0adfcd0f7/bitcoinj-money/src/main/java/com/msgilligan/bitcoinj/money/BaseXChangeExchangeRateProvider.java
