### ISSUE TITLE
Create Java 9+ examples

### ISSUE THREAD

**Issue by keilw** [JavaMoney/javamoney-examples#30]
For Java 9 and (as soon as issues like https://github.com/JavaMoney/jsr354-api/issues/71 can be resolved) also Java 10 there should be dedicated examples. 
If it's possible to build some of them as **multi-version JAR files** for Java 9, 10 or below it would be a plus.

Something nice would be
- [ ] Java 9 JShell currency converter
- [x] Java 10 var usage

**Comment by Daniel-Dos** [comment]
Hi, 

I try do this . 

.

**Comment by keilw** [comment]
We postpone JShell to a later milestone
